import type { Command } from "commander";
import { getContainer } from "../setup.js";
import { formatJson } from "../formatters.js";
import { logger } from "../logger.js";

export function registerAuditCommand(program: Command) {
  program
    .command("audit")
    .description("Generate a compliance assessment report for an AI system")
    .requiredOption("-d, --description <text>", "Description of the AI system")
    .option("-l, --legislation <id>", "Legislation ID", "eu-ai-act")
    .option("-r, --role <role>", "Role: provider, deployer, or unknown", "unknown")
    .option("-s, --signals <json>", "Structured signals as JSON")
    .option("-t, --turnover <number>", "Annual global turnover in EUR")
    .option("--sme", "Flag as SME/startup")
    .option("-f, --format <format>", "Output format: json or markdown", "json")
    .action(async (options) => {
      const { container, cleanup } = await getContainer();
      try {
        let signals: Record<string, unknown> | undefined;
        if (options.signals) {
          try {
            signals = JSON.parse(options.signals);
          } catch {
            console.error("Error: --signals must be valid JSON");
            process.exit(1);
          }
        }

        const report = await container.generateAuditReport.execute({
          legislationId: options.legislation,
          systemDescription: options.description,
          role: options.role,
          signals,
          annualTurnoverEur: options.turnover ? Number(options.turnover) : undefined,
          isSme: options.sme ?? false,
        });

        if (options.format === "markdown") {
          console.log(renderMarkdown(report));
        } else {
          console.log(formatJson(report));
        }
      } finally {
        await cleanup();
      }
    });
}

function renderMarkdown(report: any): string {
  const lines: string[] = [];
  lines.push("# Compliance Assessment Report");
  lines.push("");
  lines.push(`**Generated:** ${report.metadata.generatedAt}`);
  lines.push(`**Legislation:** ${report.metadata.legislationName}`);
  lines.push(`**Confidence:** ${report.confidence.overall} (signal completeness: ${Math.round(report.confidence.signalCompleteness * 100)}%)`);
  lines.push("");
  lines.push("## System Description");
  lines.push(report.systemDescription);
  lines.push("");
  lines.push("## Risk Classification");
  lines.push(`- **Level:** ${report.classification.riskLevel}`);
  lines.push(`- **Confidence:** ${report.classification.confidence}`);
  lines.push(`- **Basis:** ${report.classification.basis}`);
  if (report.classification.matchedCategory) {
    lines.push(`- **Category:** ${report.classification.matchedCategory}`);
  }
  lines.push("");
  if (report.obligations.length > 0) {
    lines.push(`## Obligations (${report.obligations.length})`);
    lines.push("| # | Obligation | Article | Category |");
    lines.push("|---|-----------|---------|----------|");
    report.obligations.forEach((o: any, i: number) => {
      lines.push(`| ${i + 1} | ${o.obligation} | ${o.article} | ${o.category} |`);
    });
    lines.push("");
  }
  if (report.assessments.length > 0) {
    lines.push("## Assessments");
    for (const a of report.assessments) {
      lines.push(`### ${a.name}`);
      lines.push(a.reasoning);
      lines.push("");
    }
  }
  if (report.penaltyExposure) {
    lines.push("## Penalty Exposure");
    lines.push(`- **Tier:** ${report.penaltyExposure.highestTier}`);
    lines.push(`- **Maximum Fine:** \u20AC${report.penaltyExposure.maxFine.toLocaleString()}`);
    lines.push(`- **Explanation:** ${report.penaltyExposure.explanation}`);
    lines.push("");
  }
  if (report.documentationChecklist) {
    lines.push("## Technical Documentation");
    for (const item of report.documentationChecklist) {
      lines.push(`- [ ] **${item.item}. ${item.title}** \u2014 ${item.description}`);
    }
    lines.push("");
  }
  if (report.recommendations.length > 0) {
    lines.push("## Recommendations");
    report.recommendations.forEach((r: string, i: number) => {
      lines.push(`${i + 1}. ${r}`);
    });
    lines.push("");
  }
  if (report.citations.length > 0) {
    lines.push("## Citations");
    for (const c of report.citations) {
      lines.push(`- **${c.article}** \u2014 ${c.title}: ${c.summary} ([EUR-Lex](${c.url}))`);
    }
    lines.push("");
  }
  lines.push("---");
  lines.push("*This report is generated by Lexius and does not constitute legal advice.*");
  return lines.join("\n");
}
